name: chatopia
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 国际化支持
    sdk: flutter
  intl: ^0.19.0          # 国际化代码生成
  go_router: ^14.8.1     # 路由
  http: ^1.3.0           # HTTP 请求
  provider: ^6.1.2       # 状态管理
  shared_preferences: ^2.2.1 # 本地存储（用于保存语言偏好）
  google_fonts: ^6.1.0 # 使用Google字体包

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.0     # ARB 文件生成工具

flutter:
  uses-material-design: true
  generate: true         # 启用代码生成（如国际化）
  fonts:
    - family: Pacifico
      fonts:
        - asset: lib/assets/fonts/Pacifico-Regular.ttf

flutter_intl:
  enabled: true
  # 指定生成的目录路径
  output_dir: lib/l10n/generated
  arb_dir: lib/l10n   # ARB 文件的目录
  template_arb_file: app_en_US.arb